### ISSUE TITLE
Please add Empowered Augment Rune

### ISSUE THREAD

**Issue by ghankins** [Adirelle/AdiButtonAuras#188] opened 2015-07-14 22:01 UTC
I wrote a user rule but I don't see how to select it to activate it.

return SelfBuffs {
    175456, -- Hyper Augmentation
}

**Comment by Rainrider** [comment] 2015-07-19 19:56
This is probably an issue in LibItemBuffs. I'll take a look into it next week.

**Comment by ghankins** [comment] 2015-07-19 20:20
Thanks, is there an example of how to select a user rule?  I looked through all of the documentation but don't see how to make it active on the button setting.

**Comment by Rainrider** [comment] 2015-07-19 21:06
I think the problem is that the buff id has to be mapped to the item id. Please try the following:
```
return SelfBuffAliases {
	item:118630, -- Hyper Augment Rune
	175456, -- Hyper Augmentation
}
```

**Comment by ghankins** [comment] 2015-07-20 22:19
Thanks, this ended up working after a UI reload.  Not sure why I had to reload the UI, but after I did there was a check box to select the user rule.

return SelfBuffAliases {
    "item:128475", -- Empowered Augment Rune
    175456, -- Hyper Augmentation
}

There are three Augment Runes and two Empowered Augment Runes (Horde and Alliance).
http://www.wowhead.com/search?q=augment+rune

Each grants one of three buffs (Hyper Augmentation, Focus Augmentation, Stout Augmentation).

All of these would need to be fixed in LibItemBuffs to account for all of the combinations.

Thanks again!  This is a great AddOn :-)!

**Comment by Rainrider** [comment] 2015-07-20 23:24
The proper faction/class/spec independent rule for the empowered runes would be:
```lua
return SelfBuffAliases {
	{
		"item:128482", -- Empowered Augment Rune (Alliance)
		"item:128475", -- Empowered Augment Rune (Horde)
	},
	{
		175439, -- Stout Augmentation
		175456, -- Hyper Augmentation
		175457, -- Focus Augmentation
	}
}
``` 
Sadly you have to create separate rules for the normal augment runes, since those only apply a single buff. However you can make a single user rule return several custom rules. Try this for a complete solution:
```lua
return {
	SelfBuffAliases {
		{
			"item:118630", -- Hyper Augment Rune
			"item:128475", -- Empowered Augment Rune (Horde)
			"item:128482", -- Empowered Augment Rune (Alliance)
		},
		175456, -- Hyper Augmentation
	},

	SelfBuffAliases {
		{
			"item:118631", -- Stout Augment Rune
			"item:128475", -- Empowered Augment Rune (Horde)
			"item:128482", -- Empowered Augment Rune (Alliance)
		},
		175439, -- Stout Augmentation
	},

	SelfBuffAliases {
		{
			"item:118632", -- Focus Augment Rune
			"item:128475", -- Empowered Augment Rune (Horde)
			"item:128482", -- Empowered Augment Rune (Alliance)
		},
		175457, -- Focus Augmentation
	},
}
```

**Comment by ghankins** [comment] 2015-07-21 14:08
Awesome, this works great and I tested it on my hunter for Hyper Augmentation using both the Hyper and Empowered Augment Rune (Horde).

If you wanted to do a bit of cleanup, there's a default rule for the Empowered Augment Rune that doesn't work: Show the "good" border when your buff Empower is found on yourself.

**Comment by Rainrider** [comment] 2015-08-05 21:37
ABA tries to handle "unknown" items by using the API to get the item's spell. Empower (190668) is what it gets, so it creates a rule for that. Empower however is just a trigger spell and its effects are not traceable by the API, so we have to add those as special cases in LibItemBuffs.

**Comment by Adirelle** [comment] 2015-08-07 09:31
Should be fixed https://github.com/Adirelle/LibItemBuffs-1.0/commit/1e33e6e8e8a6b539e0df152b6f35d588ea353ef2, as soon as a new version is embedded within ABA.

**Comment by Rainrider** [comment] 2015-08-07 18:00
Just tagged a release on wowace, which includes the updates. You could safely remove your user rule.

**Closed by Rainrider** 2015-08-07 18:00 UTC
