### ISSUE TITLE
Legendary Rings don't show a border

### ISSUE THREAD

**Issue by tordenflesk** [Adirelle/AdiButtonAuras#189] opened 2015-08-01 11:30 UTC
Legendary Rings don't show a border.

**Comment by Rainrider** [comment] 2015-08-05 21:20
Please try the following user rule for the time being:
```lua
return {
	-- The Savage Hollows, DPS only
	BuffAliases {
		{
			"item:124634", -- Thorasus, the Stone Heart of Draenor
			"item:124635", -- Nithramus, the All-Seer
			"item:124636", -- Maalus, the Blood Drinker
		},
		{
			187616, -- Nithramus
			187619, -- Thorasus
			187620, -- Maalus
		}
	},
	-- Tanks only
	BuffAliases {
		"item:124637", -- Sanctus, Sigil of the Unbroken
		187617, -- Sanctus
	},
	-- Heal only
	BuffAliases {
		"item:124638", -- Etheralus, the Eternal Reward
		187618, -- Etheralus
	},
}
```

**Comment by tordenflesk** [comment] 2015-08-05 22:36
I’m only able to test Maalus, but it didn’t seem to work, no border.

**Comment by Rainrider** [comment] 2015-08-06 10:26
Did you reload the ui after adding the user rule? Can you confirm the that the ring on your action bars is green after you click on "Spells & Items" in ABA's config.

The expected behavior is to have a green border and a timer for the buff duration.

Could you also verify the id of the buff when it is active as well as the item id of the ring?

**Comment by tordenflesk** [comment] 2015-08-06 13:50
No, I didn’t. Looks to be working now. Thank you :)

**Comment by Rainrider** [comment] 2015-08-06 23:08
I added this to the [wiki](https://github.com/Adirelle/AdiButtonAuras/wiki/Example-rules) for future reference.

I'm closing the issue since LibItemBuffs has to be updated and this case along others should be handled there. The user rule is the solution for the time being.

**Comment by Adirelle** [comment] 2015-08-07 09:36
As LibItemBuffs only handle enchantments, trinkets and consummables, a new handler should be added for these items. As these items are quite exceptional, I suggest adding the rules in ABA default rules.

**Comment by Rainrider** [comment] 2015-08-07 09:42
Ok, I will add those later today

**Comment by Rainrider** [comment] 2015-08-07 17:59
Just tagged a release on wowace, which includes the changes. You can safely remove the user rule

**Comment by tordenflesk** [comment] 2015-08-07 20:40
I’ve had a chance to test it in a raid setting where someone else (one of our melee) has the responsibility of using it.

It obviously doesn’t show then.

Will try the new version and see during our next raid if I can provide you with more info if you’d like.

**Comment by Rainrider** [comment] 2015-08-08 11:40
The new version won't work too. The rule I used (BuffAliases) would only cover buffs cast by the player. That is my fault. I'll fix it later today or tommorow, sorry about that.

**Closed** 2015-08-09 15:30 UTC

**Comment by Rainrider** [comment] 2015-08-09 15:35
Please confirm it works now. The new version should be up on wowace in some minutes.

**Comment by tordenflesk** [comment] 2015-08-12 22:58
Yup, works now. Doesn’t show a countdown for the buff though.

 

 

Mvh.

Esben

**Comment by Rainrider** [comment] 2015-08-13 15:29
It should display the expiration timer. Please check your settings.

**Comment by tordenflesk** [comment] 2015-08-14 12:51
When I use it, it shows:


When someone else uses it it doesn’t:



 

 

Mvh.

Esben

**Comment by Rainrider** [comment] 2015-08-14 21:52
Does the buff you get when someone else used the trinket have a duration in the default ui?

**Comment by Rainrider** [comment] 2015-08-15 13:48
And just to be sure I understood you correctly: the green border appears in every case but the expiration timer only when you used the ring?

**Comment by tordenflesk** [comment] 2015-08-15 15:31
yup

 

 

Mvh.

Esben

**Comment by Rainrider** [comment] 2015-08-15 22:59
> Does the buff you get when someone else used the trinket ring have a duration in the default ui?
