### ISSUE TITLE
(Priest) Connect (Shadow Word:) --> Insanity / Mind Sear

### ISSUE THREAD

**Issue by Tonyleila** [Adirelle/AdiButtonAuras#153] opened 2015-01-22 22:18 UTC
1 Insanity Spell in my bars: 129197
Shadow Word: Insanity buff: 132573
Note: When you use Devouring Plague the icon of Mind Flay changes to an Insanity icon.

2 Mind Sear in my bars: 48045
Mind Sear debuff on target: 48045

3 Woud be cool to see the stacks (max 9) of Words of Mending in your action bars on your Prayer of Mending spell:
http://www.wowhead.com/spell=33076/prayer-of-mending
http://www.wowhead.com/spell=155362/word-of-mending

4 Power Word: Shield http://www.wowhead.com/spell=17/power-word-shield
Instead of showing the buff of it I woud likt to connect it to Weakened Soul debuff on myself/target:
http://www.wowhead.com/spell=6788/weakened-soul

**Comment by Tonyleila** [comment] 2015-01-22 22:38
I have checked Priest.lua to add it myself but its already in, however its not showing up :(

**Comment by Tonyleila** [comment] 2015-01-22 23:23
Note: When you use Devouring Plague the icon of Mind Flay changes to an Insanity icon.

**Comment by Tonyleila** [comment] 2015-03-11 15:59
Why is this closed? Only 1/4 of the problems I posted are fixed in the latest version :(

**Comment by Rainrider** [comment] 2015-03-11 17:53
1. Shadow Word: Insanity is now called Insanity. Mapping the buff to the altered version of Insanity is a personal preference because Mind Flay and its altered version Insanity apply a debuff, a slow (without Glyph of Mind Flay) or a stacking speed buff (with Glyph of Mind Flay). So mapping their direct (de)buffs is the standard way.

2. Adirelle/LibPlayerSpells-1.0@b01ef27da46c36b1e629b2a56f047e8b85a143cd fixes this

3. I am not sure this is the right way to do this as Prayer of Mending has stacks of its own, but I don't know the exact mechanics of the spell and suppose that is what you mean by "1/4 of the problems are fixed"

4. Power Word: Shield shows the duration of Weakened Soul if the buff Power Word: Shield is not present on the ally. So it works as intended.

**Comment by Tonyleila** [comment] 2015-03-11 18:35
When you cast "Devouring Plague" on a target your "Mind Flay" is transformed into a new spell called "Insanity" you can cast "Insanity" as long as you have the buff of http://www.wowhead.com/spell=132573/insanity.
Currently its just showing NOTHING on the insanity icon. Definitely not a personal preference.
http://i.imgur.com/jLAkKyz.jpg

**Comment by Tonyleila** [comment] 2015-03-11 18:37
4. Weakened Soul is now shown for myself if I have no target, Power Word: Shield is shown.

**Comment by Rainrider** [comment] 2015-03-11 18:52
LibPlayerSpells wasn't updated with the Insanity changes in WoD and 6.1. This is now the case with linked commit above. However I have to push a new ABA tag to wowace so that it picks up the updated libraries. Since I have other work pending on both ABA and LPS I will tag later so that I don't inflate version numbers. For the time being you can try downloading [LPS on wowace](http://www.wowace.com/addons/libplayerspells-1-0/) (or curse.com if you like that one better) and install it as a separate addon.

As for Power Word: Shield it always prioritizes the target before the player. It should respect self-cast modifiers though (I believe), so this could be a way to make the button display information about the player although you targeted something else. Please correct me if I'm wrong on that one.

**Comment by Tonyleila** [comment] 2015-03-11 19:02
No no I don't want to make Power Word: Shield  display information about the player although I targeted something else... I just want it to show the Weakened Soul debuff if I have NO target and have no Power Word: Shield buff on myself.

**Comment by Tonyleila** [comment] 2015-03-11 19:07
I have tryed updating LibPlayerSpells, now It shows the the a countdown while I'm casting Insanity - well I guess thats the default behavior - anyway I have a castbar that shows me what I'm casting it woud still make more sense to show how much time you have left of your Insanity buff instead. Its very important because you can cancel your casting of Insanity 0,2 sec before the buff runs out and then cast it again to have some more ticks of Insanity = a huge DPS increase.

**Comment by Rainrider** [comment] 2015-03-11 19:31
Its debuff is also a slow, it is not solely the duration of the cast. And if the slow is away, then you have the buff provided by the Glyph of Mind Flay, which modifies both Mind Flay and Insanity. So in my opinion it is your preference and you could use a custom rule to flash it if the change of the icon is not prominent enough for you. If you don't know how to create the rule, then please tell me so, but I'm not adding this to ABA.

**Comment by Tonyleila** [comment] 2015-03-11 19:48
I don't know how to create a rule for this :( please tell me, it was easy with InlineAuras to just put in a name or spell id and connect it to another spell but here I just so code and I can't code :(

**Comment by Rainrider** [comment] 2015-03-11 21:49
1. Open ABA's options and click on "User rules".
  2. Click on "New rule".
  3. Type `Insanity` as Title and click on "okay".
  4. Under "Class restriction" choose "Priest".
  5. Remove all the text from the "Code" box and paste in the following:
```lua
return {
	SelfBuffAliases {
		129197, -- on Insanity
		132573, -- show the Insanity (buff)
	},
}
```
  6. Click on "Accept" to save the new rule.
  7. Reload your interface.

That's all.

P.S.: There is an optional part in that case, which is a bit tricky. Do this if you don't want the other rule (for the Insanity debuff on the target) to be displayed on the button as well.
  1. Open ABA's options and click on "Spells & Items". This will show the green overlay on all buttons that have at least one rule enabled (or a red one if all rules for the button are disabled) and make the buttons not clickable. Don't do this in combat or else the menu subsections will be collapsed.
  2. Build up your Shadow Orbs on a target dummy and cast Devouring Plague to trigger Insanity by using your keyboard bindings and without closing the options panel.
  3. While your Insanity buff is up, click on the green overlay over the Insanity action button (you have to do this while the buff is up, otherwise the Insanity spell is treated as unknown and the associated rules are not loaded)
  4. Now you should see two rules in the options panel. One for your custom rule we created above and one for the Insanity debuff. You can disable the one you don't need only while the Insanity buff is still up. So either be quick with that clicking or repeat those step until you succeed.

**Comment by Tonyleila** [comment] 2015-03-11 22:35
Thank you, that fixed it for me :) but woooow the optional part was realy a bit hard to do... not without a lua error of cause (in combat bug I guess) and 3 sec to read what of the three option I have to disable is a bit uhhgg. If I remember right Inline Auras had a better config for this showing all spells you ever casted in a list. Anyway thank you very much!

**Comment by Rainrider** [comment] 2015-03-11 23:27
This is a seldom case because of the spell mechanic. It is also much effort for something that provides near zero benefit and is probably done better with other tools. But this again is just my opinion. I don't see ABA as a complete replacement of a (de)buff tracker, especially because it usually provides information only about a single aura at a time (and this is its major strength too!). Glad I could help you though.

InlineAuras had other issues :)

**Closed by Rainrider** 2015-03-11 23:27 UTC
